import Head from "next/head"
import PageSpinner from "../../../components/PageSpinner"
import OrganizationForm from "../../../components/organizations/OrganizationForm"
import Header from "../../../components/header/Header"
import { useUser } from "../../../hooks/useUser"
import { useEffect } from "react"
import { useRouter } from "next/router"
import { useFetch } from "../../../hooks/useFetch"

export default function NewOrganization() {
  const [isAuthenticated, isLoadingUser] = useUser()
  const router = useRouter()

  useEffect(() => {
    if (!isLoadingUser && !isAuthenticated) {
      router.push("/login")
    }
  }, [router, isAuthenticated, isLoadingUser])

  const { id } = router.query
  // eslint-disable-next-line no-empty
  const isAddMode = !id

  const [organizationData, isLoading] = useFetch({
    url: `/organizations/${id}`,
    method: "get",
  })

  return (
    <>
      <Head>
        <title>Edit Organization - ZmartBuild</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!isAuthenticated || isLoadingUser || isLoading ? (
        <div className="grid h-screen place-items-center">
          <PageSpinner />
        </div>
      ) : (
        <>
          <Header />
          <main className="">
            <OrganizationForm isAddMode={isAddMode} organizationData={organizationData} />
          </main>
        </>
      )}
    </>
  )
}
