import Head from "next/head"
import PageSpinner from "../../../components/PageSpinner"
import ProjectForm from "../../../components/ProjectForm"
import Header from "../../../components/header/Header"
import { useUser } from "../../../hooks/useUser"
import { useEffect } from "react"
import { useRouter } from "next/router"

export default function NewProject() {
  const router = useRouter()
  const [isAuthenticated, isLoadingUser] = useUser()

  useEffect(() => {
    if (!isLoadingUser && !isAuthenticated) {
      router.push("/login")
    }
  }, [router, isAuthenticated, isLoadingUser])

  return (
    <>
      <Head>
        <title>New Project - ZmartBuild</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!isAuthenticated || isLoadingUser ? (
        <div className="grid h-screen place-items-center">
          <PageSpinner />
        </div>
      ) : (
        <>
          <Header />
          <main>
            <ProjectForm />
          </main>
        </>
      )}
    </>
  )
}