import Head from "next/head"
import PageSpinner from "../../../../components/PageSpinner"
import Header from "../../../../components/header/Header"
import { useUser } from "../../../../hooks/useUser"
import LoadModel from "../../../../components/Model"
import { useEffect } from "react"
import { useRouter } from "next/router"
import { useMockFetch } from "../../../../hooks/useFetch"

export default function NewProject() {
  const [isAuthenticated, isLoadingUser] = useUser()
  const router = useRouter()
  const [subproject, isLoading, error] = useMockFetch({
    url: `/subprojects/${router.query.idSubProject}`,
    method: "get",
  })

  useEffect(() => {
    if (!isLoadingUser && !isAuthenticated) {
      router.push("/login")
    }
  }, [router, isAuthenticated, isLoadingUser])

  return (
    <>
      <Head>
        <title>ZmartBuild</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!isAuthenticated || isLoadingUser ? (
        <div className="grid h-screen place-items-center">
          <PageSpinner />
        </div>
      ) : (
        <>
          <Header />
          <main>
            {isLoading && !error && (
              <div className="grid h-screen place-items-center">
                <PageSpinner />
              </div>
            )}

            {!isLoading && error && <div>{JSON.stringify(error)}</div>}
            <div className="grid justify-items-center">
              <h1>{subproject?.name}</h1>
              <LoadModel url={subproject?.modelUrl} />
            </div>
          </main>
        </>
      )}
    </>
  )
}
