import { useMockFetch } from "../../hooks/useFetch"
import Head from "next/head"
import PrimaryButton from "../../components/basics/PrimaryButton"
import PrimaryLink from "../../components/basics/PrimaryLink"
import Header from "../../components/header/Header"
import { useUser } from "../../hooks/useUser"
import { useEffect } from "react"
import { useRouter } from "next/router"
import PageSpinner from "../../components/PageSpinner"
import SubprojectCard from "../../components/subprojects/SubprojectCard"

export default function Home() {
  const router = useRouter()
  const [subprojects, isLoading, error] = useMockFetch({
    url: "/subprojects",
    method: "get",
  })
  const [isAuthenticated, isLoadingUser] = useUser()

  useEffect(() => {
    if (!isLoadingUser && !isAuthenticated) {
      router.push("/login")
    }
  }, [router, isAuthenticated, isLoadingUser])

  return (
    <>
      <Head>
        <title>Subprojects - ZmartBuild</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!isAuthenticated || isLoadingUser ? (
        <div className="grid h-screen place-items-center">
          <PageSpinner />
        </div>
      ) : (
        <>
          <Header />
          <main>
            <div className="flex-col items-center text-center my-8">
              <h1 className="text-3xl md:text-4xl lg:text-5xl font-semibold">Subprojects</h1>
              <br />
              {/* <h4>From {project.title}</h4> */}
            </div>

            {isLoading && !error && (
              <div className="grid h-screen place-items-center">
                <PageSpinner />
              </div>
            )}

            {!isLoading && error && <div>{JSON.stringify(error)}</div>}

            <section className="grid h-screen place-items-center">
              <PrimaryLink linkTo="/newsubproject">
                <PrimaryButton disabled={false} className="border hover:shadow-md">
                  New subproject
                </PrimaryButton>
              </PrimaryLink>

              {subprojects &&
                subprojects.map((subproject) => {
                  return <SubprojectCard key={subproject.id} subproject={subproject} />
                })}
            </section>
          </main>
        </>
      )}
    </>
  )
}
