import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>DS Frontend</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="flex-col items-center text-center">
          <h1 className="text-6xl">Hello World!</h1>
        </div>
      </main>
    </>
  )
}
