import Head from "next/head"
import Header from "../components/header/Header"
import Invitation from "../components/Invitation"

import { useMockFetch } from "../hooks/useFetch"

export default function Invitations() {
  const [invitations, isLoading, error] = useMockFetch({ url: "/myinvitations/", method: "get" })

  {
    isLoading && !error && <div>Loading invitations</div>
  }

  {
    !isLoading && error && <div>{JSON.stringify(error)}</div>
  }

  return (
    <>
      <Head>
        <title>My Invitations</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <div className="flex-col items-center text-center my-8">
          <h1 className="text-3xl md:text-4xl lg:text-5xl font-semibold">My Invitations</h1>
        </div>

        {invitations && (
          <section className="grid h-screen place-items-center">
            {invitations.map((invitation) => {
              return <Invitation key={invitation.id} data={invitation} />
            })}
          </section>
        )}
      </main>
    </>
  )
}
