import { useState, useContext } from "react"
import AuthContext from "../stores/AuthContext"

import Head from "next/head"
import Header from "../components/Header"
import MyInvitations from "../components/MyInvitations"

import { apiGet } from "../services/api"

export default function Invitations() {
  const { user, isLoading } = useContext(AuthContext)
  const [data, setData] = useState(null)

  if (!isLoading & (data === null)) {
    // SetData must be call only when apiGet stops being a promise
    apiGet("myinvitations", { params: { id: user.id } }).then((info) => setData(info))
  }

  return (
    <>
      <Head>
        <title>My Invitations</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <div className="flex-col items-center text-center my-8">
          <h1 className="text-3xl md:text-4xl lg:text-5xl font-semibold">My Invitations</h1>
        </div>
      </main>

      {data !== null ? <MyInvitations data={data} /> : null}
    </>
  )
}
