import { useState } from "react"

import Head from "next/head"
import Header from "../components/Header"
import Model from "../components/Model"
import MyProyects from "../components/MyProjects"

import { apiGet } from "../services/api"

export default function Home() {
  const [data, setData] = useState(null)

  if (data === null) {
    // SetData must be call only when apiGet stops being a promise
    apiGet("myprojects").then((info) => setData(info))
  }

  return (
    <>
      <Head>
        <title>My Projects</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <div className="flex-col items-center text-center my-8">
          <h1 className="text-3xl md:text-4xl lg:text-5xl font-semibold">My Projects</h1>
        </div>
      </main>

      {data !== null ? <MyProyects data={data} /> : null}

      <Model name={"futuristic"} scale={0.1} autoRotate={false} />
    </>
  )
}
