import Head from "next/head"
import PageSpinner from "../components/PageSpinner"

import OrganizationForm from "../components/organizations/OrganizationForm"
import Header from "../components/header/Header"
import { useUser } from "../hooks/useUser"

export default function NewOrganization() {
  const [isAuthenticated, isLoadingUser] = useUser()

  return (
    <>
      <Head>
        <title>New organization - ZmartBuild</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!isAuthenticated || isLoadingUser ? (
        <div className="grid h-screen place-items-center">
          <PageSpinner />
        </div>
      ) : (
        <>
          <Header />
          <main className="">
            <OrganizationForm />
          </main>
        </>
      )}
    </>
  )
}
