import Head from "next/head"
import { useRouter } from "next/router"
import { useContext, useEffect } from "react"

import Header from "../components/header/Header"
import PageSpinner from "../components/PageSpinner"
import ProfileCard from "../components/Profile"
import AuthContext from "../stores/AuthContext"
import { useUser } from "../hooks/useUser"

export default function Profile() {
  const [isAuthenticated, isLoadingUser] = useUser()
  const { isLoading } = useContext(AuthContext)
  const router = useRouter()

  useEffect(() => {
    if (!isLoadingUser && !isAuthenticated) {
      router.push("/login")
    }
  }, [router, isAuthenticated, isLoadingUser])

  return (
    <>
      <Head>
        <title>Profile - ZmartBuild</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!isAuthenticated || isLoadingUser ? (
        <div className="grid h-screen place-items-center">
          <PageSpinner />
        </div>
      ) : (
        <>
          <Header />

          <main>
            <div className="flex-col items-center text-center my-8">
              <h1 className="text-3xl md:text-4xl lg:text-5xl font-semibold">My Profile</h1>
            </div>

            {isLoading && (
              <div className="grid place-items-center h-72 lg:h-80">
                <PageSpinner />
              </div>
            )}
            <div className="flex flex-row min-h-screen justify-center items-cente">
              <ProfileCard/>
            </div>
          </main>
        </>
      )}
    </>
  )
}
